# -*- coding: utf-8 -*-
"""kaggle_mercado_livre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hgOcCfrgxhWqlOxHoCMqgrcoHk2_0P_
"""

#conecta o colab com o google drive, crie um diretório no seu drive chamado kaggle e ponha os arquivos nele

import numpy as np

import pandas as pd

train_csv_local = '/home/joaopaulo/Documentos/Mestrado/competição/train.csv'
test_csv_local = '/home/joaopaulo/Documentos/Mestrado/competição/test.csv'

#carrega o conjunto de treino e teste para um panda df
train_df = pd.read_csv(train_csv_local, header = 0)
test_df = pd.read_csv(test_csv_local, header = 0)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
#vetorizando o conjunto de treino
vectorizer = TfidfVectorizer(token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b',max_features=200)
encoder = LabelEncoder()
X_train = vectorizer.fit_transform(train_df['title'])
y_train = encoder.fit_transform(train_df['category'])


print(X_train.shape)

print(y_train.shape)


classes = np.array(encoder.classes_)
print(repr(classes))
print(np.array(vectorizer.get_feature_names()))

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

#visualizando frenquencia das classes
unique, counts = np.unique(y_train, return_counts=True)
plt.bar(unique,counts)
plt.title('Class Frequency')
plt.xlabel('Class')
plt.ylabel('Frequency')

#plt.show()


